require("user.option")
require("user.keymap")
require("user.plugins")
require("user.lsp")
-- config plugins
require("user.config.colorscheme")
require("user.config.nvim-tree")
require("user.config.alpha")
require("user.config.autopairs")
require("user.config.bufferline")
require("user.config.cmp")
require("user.config.comment")
require("user.config.illuminate")
require("user.config.impatient")
require("user.config.lualine")
require("user.config.project")
require("user.config.telescope")
require("user.config.toggleterm")
require("user.config.treesitter")
require("user.config.cmp")
require("user.config.whichley")
require("user.config.renamer")

